name: MC_QQ
version: 1.0.0
main: com.scareye.mcqq.MC_QQ
api-version: 1.16
authors: [ 17TheWord ]
description: 基于NoneBot的与Minecraft Server互通消息的插件
website: https://github.com/17TheWord/nonebot-plugin-mcqq
