# 是否启用插件
# 默认启用
enable_mc_qq: true

# 请在冒号后填写 WebSocket 服务的地址端口号。
# 只填写数字即可。
# 冒号后需要空一格！
# 若不填写，则地址默认为 127.0.0.1 ，端口默认为 8765
websocket_hostname: 127.0.0.1
websocket_port: 8765

# 发送到群消息中，玩家昵称与消息之间的符号
# 默认为 “说：”
# 例如：
#   17TheWord ： 你好
say_way: "说："

# 是否启用 玩家死亡事件监听
# 开启后，当玩家死亡时，Bot会推送信息
# 默认启用
death_message: true

# 是否启用 加入/离开 服务器监听
# 开启后，当玩家 加入/离开 服务器时，Bot会随推送信息
# 默认打开
# 例如：
#   17TheWord 加入了服务器
#   17TheWord 离开了服务器
join_quit: true
