name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Install dependencies
      run: poetry install --no-root --no-dev

    - name: Build and publish
      run: poetry publish --build